/* main.c generated by valac 0.56.18, the Vala compiler
 * generated from main.vala, do not modify */

#include <glib-object.h>
#include <thunarx/thunarx.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_HELLO_PLUGIN (hello_plugin_get_type ())
#define HELLO_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HELLO_PLUGIN, HelloPlugin))
#define HELLO_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HELLO_PLUGIN, HelloPluginClass))
#define IS_HELLO_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HELLO_PLUGIN))
#define IS_HELLO_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HELLO_PLUGIN))
#define HELLO_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HELLO_PLUGIN, HelloPluginClass))

typedef struct _HelloPlugin HelloPlugin;
typedef struct _HelloPluginClass HelloPluginClass;
typedef struct _HelloPluginPrivate HelloPluginPrivate;
enum  {
	HELLO_PLUGIN_0_PROPERTY,
	HELLO_PLUGIN_NUM_PROPERTIES
};
static GParamSpec* hello_plugin_properties[HELLO_PLUGIN_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _HelloPlugin {
	GObject parent_instance;
	HelloPluginPrivate * priv;
};

struct _HelloPluginClass {
	GObjectClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	HelloPlugin* self;
	GtkWidget* window;
	GList* files;
};

static gpointer hello_plugin_parent_class = NULL;
static ThunarxMenuProviderIface * hello_plugin_thunarx_menu_provider_parent_iface = NULL;

VALA_EXTERN GType hello_plugin_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HelloPlugin, g_object_unref)
static GList* hello_plugin_real_get_file_menu_items (ThunarxMenuProvider* base,
                                              GtkWidget* window,
                                              GList* files);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_);
static void ___lambda4__thunarx_menu_item_activate (ThunarxMenuItem* _sender,
                                             gpointer self);
static GList* hello_plugin_real_get_folder_menu_items (ThunarxMenuProvider* base,
                                                GtkWidget* window,
                                                ThunarxFileInfo* folder);
static GList* hello_plugin_real_get_dnd_menu_items (ThunarxMenuProvider* base,
                                             GtkWidget* window,
                                             ThunarxFileInfo* folder,
                                             GList* files);
VALA_EXTERN HelloPlugin* hello_plugin_new (void);
VALA_EXTERN HelloPlugin* hello_plugin_construct (GType object_type);
static GType hello_plugin_get_type_once (void);
VALA_EXTERN void thunar_extension_initialize (ThunarxProviderPlugin* plugin);
VALA_EXTERN void thunar_extension_shutdown (void);
VALA_EXTERN void thunar_extension_list_types (GType** types,
                                  gint* types_length1);

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		HelloPlugin* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->window);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}

static void
__lambda4_ (Block1Data* _data1_)
{
	HelloPlugin* self;
	gchar* msg = NULL;
	gchar* _tmp0_;
	GtkWindow* parent_window = NULL;
	GtkWindow* _tmp1_;
	GtkMessageDialog* dialog = NULL;
	GtkMessageDialog* _tmp2_;
	self = _data1_->self;
	_tmp0_ = g_strdup_printf ("You selected %u file(s).", g_list_length (_data1_->files));
	msg = _tmp0_;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_data1_->window, gtk_window_get_type ()) ? ((GtkWindow*) _data1_->window) : NULL);
	parent_window = _tmp1_;
	_tmp2_ = (GtkMessageDialog*) gtk_message_dialog_new (parent_window, GTK_DIALOG_MODAL, GTK_MESSAGE_INFO, GTK_BUTTONS_OK, "%s", msg);
	g_object_ref_sink (_tmp2_);
	dialog = _tmp2_;
	gtk_dialog_run ((GtkDialog*) dialog);
	gtk_widget_destroy ((GtkWidget*) dialog);
	_g_object_unref0 (dialog);
	_g_object_unref0 (parent_window);
	_g_free0 (msg);
}

static void
___lambda4__thunarx_menu_item_activate (ThunarxMenuItem* _sender,
                                        gpointer self)
{
	__lambda4_ (self);
}

static GList*
hello_plugin_real_get_file_menu_items (ThunarxMenuProvider* base,
                                       GtkWidget* window,
                                       GList* files)
{
	HelloPlugin * self;
	Block1Data* _data1_;
	GtkWidget* _tmp0_;
	GList* items = NULL;
	ThunarxMenuItem* item = NULL;
	ThunarxMenuItem* _tmp1_;
	ThunarxMenuItem* _tmp2_;
	GList* result;
	self = (HelloPlugin*) base;
	g_return_val_if_fail (window != NULL, NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = _g_object_ref0 (window);
	_g_object_unref0 (_data1_->window);
	_data1_->window = _tmp0_;
	_data1_->files = files;
	items = NULL;
	_tmp1_ = thunarx_menu_item_new ("HelloPlugin::say-hello", "Say Hello", "Shows a dialog", "dialog-information");
	item = _tmp1_;
	g_signal_connect_data (item, "activate", (GCallback) ___lambda4__thunarx_menu_item_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp2_ = _g_object_ref0 (item);
	items = g_list_append (items, _tmp2_);
	result = items;
	_g_object_unref0 (item);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}

static GList*
hello_plugin_real_get_folder_menu_items (ThunarxMenuProvider* base,
                                         GtkWidget* window,
                                         ThunarxFileInfo* folder)
{
	HelloPlugin * self;
	GList* result;
	self = (HelloPlugin*) base;
	g_return_val_if_fail (window != NULL, NULL);
	g_return_val_if_fail (folder != NULL, NULL);
	result = NULL;
	return result;
}

static GList*
hello_plugin_real_get_dnd_menu_items (ThunarxMenuProvider* base,
                                      GtkWidget* window,
                                      ThunarxFileInfo* folder,
                                      GList* files)
{
	HelloPlugin * self;
	GList* result;
	self = (HelloPlugin*) base;
	g_return_val_if_fail (window != NULL, NULL);
	g_return_val_if_fail (folder != NULL, NULL);
	result = NULL;
	return result;
}

HelloPlugin*
hello_plugin_construct (GType object_type)
{
	HelloPlugin * self = NULL;
	self = (HelloPlugin*) g_object_new (object_type, NULL);
	return self;
}

HelloPlugin*
hello_plugin_new (void)
{
	return hello_plugin_construct (TYPE_HELLO_PLUGIN);
}

static void
hello_plugin_class_init (HelloPluginClass * klass,
                         gpointer klass_data)
{
	hello_plugin_parent_class = g_type_class_peek_parent (klass);
}

static void
hello_plugin_thunarx_menu_provider_interface_init (ThunarxMenuProviderIface * iface,
                                                   gpointer iface_data)
{
	hello_plugin_thunarx_menu_provider_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_file_menu_items = (GList* (*) (ThunarxMenuProvider*, GtkWidget*, GList*)) hello_plugin_real_get_file_menu_items;
	iface->get_folder_menu_items = (GList* (*) (ThunarxMenuProvider*, GtkWidget*, ThunarxFileInfo*)) hello_plugin_real_get_folder_menu_items;
	iface->get_dnd_menu_items = (GList* (*) (ThunarxMenuProvider*, GtkWidget*, ThunarxFileInfo*, GList*)) hello_plugin_real_get_dnd_menu_items;
}

static void
hello_plugin_instance_init (HelloPlugin * self,
                            gpointer klass)
{
}

static GType
hello_plugin_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (HelloPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hello_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HelloPlugin), 0, (GInstanceInitFunc) hello_plugin_instance_init, NULL };
	static const GInterfaceInfo thunarx_menu_provider_info = { (GInterfaceInitFunc) hello_plugin_thunarx_menu_provider_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType hello_plugin_type_id;
	hello_plugin_type_id = g_type_register_static (G_TYPE_OBJECT, "HelloPlugin", &g_define_type_info, 0);
	g_type_add_interface_static (hello_plugin_type_id, thunarx_menu_provider_get_type (), &thunarx_menu_provider_info);
	return hello_plugin_type_id;
}

GType
hello_plugin_get_type (void)
{
	static volatile gsize hello_plugin_type_id__once = 0;
	if (g_once_init_enter (&hello_plugin_type_id__once)) {
		GType hello_plugin_type_id;
		hello_plugin_type_id = hello_plugin_get_type_once ();
		g_once_init_leave (&hello_plugin_type_id__once, hello_plugin_type_id);
	}
	return hello_plugin_type_id__once;
}

void
thunar_extension_initialize (ThunarxProviderPlugin* plugin)
{
	g_return_if_fail (plugin != NULL);
	thunarx_provider_plugin_set_resident (plugin, TRUE);
}

void
thunar_extension_shutdown (void)
{
}

void
thunar_extension_list_types (GType** types,
                             gint* types_length1)
{
	GType* _vala_types = NULL;
	gint _vala_types_length1 = 0;
	GType* _tmp0_;
	_tmp0_ = g_new0 (GType, 1);
	_tmp0_[0] = TYPE_HELLO_PLUGIN;
	_vala_types = (g_free (_vala_types), NULL);
	_vala_types = _tmp0_;
	_vala_types_length1 = 1;
	if (types) {
		*types = _vala_types;
	} else {
		_vala_types = (g_free (_vala_types), NULL);
	}
	if (types_length1) {
		*types_length1 = _vala_types_length1;
	}
}

